# Generated by Django 5.2.14 on 2026-05-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_add_budget_amount_to_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='budget_amount',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
