# Generated by Django 5.2.14 on 2026-05-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_stop_budget_amount_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
